# Generated by Django 5.2.5 on 2025-08-20 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('wifi', 'WiFi'), ('app', 'App Install'), ('restriction', 'Restriction')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(db_index=True, max_length=120)),
                ('os_type', models.CharField(choices=[('android', 'Android'), ('chrome', 'ChromeOS')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('last_check_in', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.owner')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.policy')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='policies',
            field=models.ManyToManyField(related_name='devices', through='core.DevicePolicy', to='core.policy'),
        ),
        migrations.AddIndex(
            model_name='devicepolicy',
            index=models.Index(fields=['device', 'status'], name='core_device_device__7b2eaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepolicy',
            unique_together={('device', 'policy')},
        ),
    ]
